import { useState } from "react";
import { ArrowUpRight, ListFilter, Plus, RefreshCw, Sparkles } from "lucide-react";
import { DISCOVERY_PAGE_SIZE } from "../models.js";
import type { DashboardState, ResumeSummary, JobDiscoveryPreferences } from "../models.js";
import type { Act, Analyze } from "../ui-types.js";
import { dateTime, isNewJob } from "../data.js";
import { dateLabel } from "../format.js";

export function Discovery({ state, resumes, busy, act, analyze, analysisPending }: { state: DashboardState; resumes: ResumeSummary[]; busy: boolean; act: Act; analyze: Analyze; analysisPending: boolean }) {
  const [prefs, setPrefs] = useState<JobDiscoveryPreferences>(state.preferences);
  const [category, setCategory] = useState("all");
  const jobs = state.discovery.jobs;
  const categoryOf = (job: typeof jobs[number]) => isNewJob(job) ? "new" : dateTime(job.publishedAt) === null ? "unknown" : "older";
  const categoryLabels: Record<string, string> = { new: "Son 7 gün", unknown: "Tarih bilinmiyor", older: "Diğer ilan" };
  const visibleJobs = jobs.filter(j => category === "all" || categoryOf(j) === category);
  return <><section className="panel"><div className="section-heading"><div><h2>Yeni fırsatları bul</h2><p>Kariyer.net profil önerileri · CV seçimin ayrıntılı AI analizinde kullanılır.</p></div><span className="muted">Son yenileme: {dateLabel(state.discovery.fetchedAt)}</span></div>
    <form onSubmit={e => { e.preventDefault(); void act({ action: "search", preferences: prefs, page: 1 }); }}><fieldset disabled={busy}><div className="discovery-filters"><label>Hedef pozisyon<input value={prefs.keyword} maxLength={200} placeholder="Örn. Frontend geliştirici" onChange={e => setPrefs({ ...prefs, keyword: e.target.value })} /></label><label>Konum<select value={prefs.cities[0] || ""} onChange={e => setPrefs({ ...prefs, cities: e.target.value ? [e.target.value] : [] })}><option value="">Tüm konumlar</option>{state.discovery.options.cities.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Çalışma modeli<select value={prefs.workModels[0] || ""} onChange={e => setPrefs({ ...prefs, workModels: e.target.value ? [e.target.value] : [] })}><option value="">Tüm modeller</option>{state.discovery.options.workModels.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label><button className="primary"><RefreshCw size={16} className={busy ? "spin" : ""} />Yenile</button></div><label className="checkbox-label"><input type="checkbox" checked={prefs.includeOlder ?? false} onChange={e => setPrefs({ ...prefs, includeOlder: e.target.checked })} />Daha eski ilanları da göster</label><p className="muted">Seçildiğinde 7 günlük sınır kaldırılır. Filtreleri uygulamak için Yenile’ye bas.</p></fieldset></form>
    {!state.discovery.fetchedAt && <p className="hint">İlk yenilemede API’nin konum ve çalışma modeli seçenekleri yüklenir. İlan araması yalnız sen yenilediğinde çalışır.</p>}
    <div className="cv-choice"><label>Uyum analizinde kullanılacak CV<select value={prefs.resumeId} onChange={e => setPrefs({ ...prefs, resumeId: e.target.value })}><option value="">CV seç</option>{resumes.map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select></label><button className="secondary" disabled={busy} onClick={() => { void act({ action: "resumes" }); }}>CV’leri getir</button><p>Analiz et’e bastığında CV ve ilan seçtiğin AI sağlayıcısına gönderilir.</p></div>
  </section>
  {!jobs.length ? <section className="panel empty"><Sparkles size={36} /><h2>{state.discovery.fetchedAt ? "Bu filtrelerle ilan bulunamadı" : "Bir sonraki fırsatın burada"}</h2><p>Yenile’ye basarak profilin için önerilen ilanları getir.</p></section> : <>
    <section className="panel discovery-results"><div className="section-heading"><div><h2>Önerilen ilanlar <span className="count-badge">{jobs.length}</span></h2><p>{state.preferences.includeOlder ? "Tüm tarihler" : "Son 7 gün arama filtresi"} · Sayfada en fazla 50 ilan. Yeni ilan etiketi doğrulanabilen yayın tarihine dayanır.</p></div><label className="select-field"><ListFilter size={16} /><select aria-label="İlan yayın tarihi filtresi" value={category} onChange={e => setCategory(e.target.value)}><option value="all">Tüm ilanlar</option><option value="new">Son 7 günde yayımlananlar</option><option value="unknown">Yayın tarihi bilinmeyenler</option><option value="older">Diğer önerilen ilanlar</option></select></label></div>
      <div className="table-wrap"><table className="application-table discovery-table"><thead><tr><th>Pozisyon / Şirket</th><th>Konum</th><th>Çalışma modeli</th><th>Yayın tarihi</th><th>İlk görüldü</th><th>İşlemler</th></tr></thead><tbody>{visibleJobs.map(j => <tr key={j.id}><td><a className="job-title" href={j.jobUrl || "https://www.kariyer.net/is-ilani/ilan-" + j.id} target="_blank" rel="noopener noreferrer">{j.title} <ArrowUpRight size={13} /></a><span className="company-name">{j.companyName || "Şirket belirtilmemiş"}</span></td><td>{j.location || "—"}</td><td>{j.workModel || "—"}</td><td>{dateLabel(j.publishedAt)}<small className={categoryOf(j) === "new" ? "new-badge" : "muted"}>{categoryLabels[categoryOf(j)]}</small></td><td>{dateLabel(j.firstSeenAt)}</td><td><div className="table-row-actions"><button className="secondary" disabled={busy || state.applications.some(a => a.jobId === j.id)} onClick={() => { void act({ action: "track", jobId: j.id }); }}><Plus size={14} />{state.applications.some(a => a.jobId === j.id) ? "Takipte" : "Takibe ekle"}</button><button className="text-button" disabled={busy || analysisPending || !prefs.resumeId} onClick={() => analyze(j.id, { resumeId: prefs.resumeId }, "CV uyum analizi · " + j.title)}><Sparkles size={14} />Uyumu analiz et</button></div></td></tr>)}</tbody></table></div>
      {!visibleJobs.length && <p className="empty-copy muted">Bu sayfada seçtiğin tarih grubunda ilan yok.</p>}
    </section>
    <div className="pagination"><button className="secondary" disabled={busy || state.discovery.currentPage <= 1} onClick={() => { void act({ action: "search", preferences: state.preferences, page: state.discovery.currentPage - 1 }); }}>Önceki</button><span>Sayfa {state.discovery.currentPage} · {state.discovery.total} önerilen ilan</span><button className="secondary" disabled={busy || state.discovery.currentPage * DISCOVERY_PAGE_SIZE >= state.discovery.total} onClick={() => { void act({ action: "search", preferences: prefs, page: state.discovery.currentPage + 1 }); }}>Sonraki</button></div>
  </>}
  </>;
}
